version: "3"
services:
  serv1:
    # replace username/repo:tag with your name and image details
    image: sd_layout
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet1
    volumes:
      - /home/pi/container/sd_proj_ip:/etc/sd_proj_ip
networks:
  webnet1:
