version: "3"
services:
  serv2:
    # replace username/repo:tag with your name and image details
    image: sd_user_registo
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8020:8020"
    networks:
      - webnet2
    volumes:
      - /home/pi/container/sd_proj_ip:/etc/sd_proj_ip
networks:
  webnet2:
