version: "3"
services:
  serv4:
    # replace username/repo:tag with your name and image details
    image: sd_horario
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8022:8022"
    networks:
      - webnet4
    volumes:
      - /home/pi/container/sd_proj_ip:/etc/sd_proj_ip
networks:
  webnet4:
